M48
; DRILL file {KiCad 9.0.7} date 2026-02-23T19:44:23-0500
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-02-23T19:44:23-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.7
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C6.756
%
G90
G05
T1
X148.031Y-129.794
X148.184Y-77.882
X193.827Y-77.699
X214.605Y-129.896
M30
